import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import URDFLoader from "urdf-loader";

import {
  applyKeyboardJointBindingDelta,
  type ApplyKeyboardJointDeltaContext,
  type KeyboardJointBinding as VendoredKeyboardJointBinding,
  type TeleopJointInfo,
} from "../vendor/cyberwave-frontend/keyboard-joint-bindings";
import { runChecklist, type ChecklistResult, type ParsedJoint } from "./checklist/runChecklist";
import { StatusLine } from "./StatusLine";

// Matches export_controller_policy.py's JSON output shape (TWIN_PREVIEW_TOOL_PLAN.md §3.5).
interface ControllerPolicyFile {
  catalog_key: string;
  name: string;
  metadata: {
    keyboard_bindings: VendoredKeyboardJointBinding[];
  };
}

// Every fixture generated by scripts/export_controller_policy.py, keyed by filename.
const policyModules = import.meta.glob<{ default: ControllerPolicyFile }>(
  "./fixtures/*.controller.json",
  { eager: true },
);

function resolvePolicy(policyKey: string): ControllerPolicyFile | null {
  for (const [path, mod] of Object.entries(policyModules)) {
    if (path.includes(policyKey)) return mod.default;
  }
  return null;
}

interface URDFJointLike {
  jointType: string;
  limit: { lower: number; upper: number; effort: number; velocity: number };
  mimicJoint?: string | null;
  setJointValue: (...values: number[]) => boolean;
}

interface URDFRobotLike extends THREE.Object3D {
  joints: Record<string, URDFJointLike>;
  setJointValue: (name: string, value: number) => boolean;
}

const DEFAULT_URDF = "Unitree/D1_T/D1_T_Gripper/urdf/d1_t_gripper.urdf";
const DEFAULT_POLICY = "d1_t_gripper";

function readParams() {
  const params = new URLSearchParams(window.location.search);
  return {
    urdf: params.get("urdf") ?? DEFAULT_URDF,
    policy: params.get("policy") ?? DEFAULT_POLICY,
  };
}

declare global {
  interface Window {
    __twinPreview?: {
      loadAsset: (urdfPath: string) => Promise<void>;
      getJointState: () => Record<string, number>;
      setJoint: (name: string, value: number) => void;
      getChecklistResult: () => ChecklistResult | null;
    };
  }
}

export function Viewer3D() {
  const mountRef = useRef<HTMLDivElement>(null);
  const [assetName, setAssetName] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [checklist, setChecklist] = useState<ChecklistResult | null>(null);

  // Mutable, non-reactive scene state — read/written every animation frame,
  // deliberately kept out of React state (matches the real frontend's own
  // jointValues-as-ref pattern, see lib/types/urdf.ts's jointAnglesRef).
  const sceneRef = useRef<{
    scene: THREE.Scene;
    camera: THREE.PerspectiveCamera;
    renderer: THREE.WebGLRenderer;
    controls: OrbitControls;
    robot: URDFRobotLike | null;
    jointValues: Record<string, number>;
    joints: TeleopJointInfo[];
    bindings: VendoredKeyboardJointBinding[];
    pressedKeys: Set<string>;
  } | null>(null);

  useEffect(() => {
    const mount = mountRef.current;
    if (!mount) return;

    const scene = new THREE.Scene();
    scene.background = new THREE.Color(0x050709);

    const camera = new THREE.PerspectiveCamera(50, mount.clientWidth / mount.clientHeight, 0.01, 100);
    camera.position.set(0.6, 0.5, 0.9);

    const renderer = new THREE.WebGLRenderer({ antialias: true });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.setSize(mount.clientWidth, mount.clientHeight);
    mount.appendChild(renderer.domElement);

    const grid = new THREE.GridHelper(4, 40, 0x0d1117, 0x0d1117);
    scene.add(grid);

    const hemi = new THREE.HemisphereLight(0xffffff, 0x222233, 1.2);
    scene.add(hemi);
    const dir = new THREE.DirectionalLight(0xffffff, 1.5);
    dir.position.set(2, 3, 2);
    scene.add(dir);

    const controls = new OrbitControls(camera, renderer.domElement);
    controls.target.set(0, 0.1, 0);
    controls.update();

    sceneRef.current = {
      scene,
      camera,
      renderer,
      controls,
      robot: null,
      jointValues: {},
      joints: [],
      bindings: [],
      pressedKeys: new Set(),
    };

    let disposed = false;

    function resize() {
      if (!mount) return;
      camera.aspect = mount.clientWidth / mount.clientHeight;
      camera.updateProjectionMatrix();
      renderer.setSize(mount.clientWidth, mount.clientHeight);
    }
    window.addEventListener("resize", resize);

    function onKeyDown(e: KeyboardEvent) {
      sceneRef.current?.pressedKeys.add(e.key.toUpperCase());
    }
    function onKeyUp(e: KeyboardEvent) {
      sceneRef.current?.pressedKeys.delete(e.key.toUpperCase());
    }
    window.addEventListener("keydown", onKeyDown);
    window.addEventListener("keyup", onKeyUp);

    // ~40Hz tick, matching the step rate keyboard-joint-bindings.ts's own
    // docs describe for the real frontend (teleop-joint-leash.ts's comment).
    const TICK_MS = 25;
    const tickInterval = window.setInterval(() => {
      const s = sceneRef.current;
      if (!s || !s.robot) return;
      for (const binding of s.bindings) {
        if (!s.pressedKeys.has(binding.key.toUpperCase())) continue;
        const context: ApplyKeyboardJointDeltaContext = {
          mode: "simulate",
          joints: s.joints,
          jointValues: s.jointValues,
          hasMqttFeedbackForJoint: () => true,
          knownJointValueKeys: Object.keys(s.jointValues),
        };
        const deltas = applyKeyboardJointBindingDelta(binding, context);
        for (const d of deltas) {
          s.jointValues[d.jointName] = d.newValue;
          s.robot.setJointValue(d.jointName, d.newValue);
        }
      }
    }, TICK_MS);

    function animate() {
      if (disposed) return;
      controls.update();
      renderer.render(scene, camera);
      requestAnimationFrame(animate);
    }
    animate();

    function fitCameraToRobot(robot: THREE.Object3D) {
      const box = new THREE.Box3().setFromObject(robot);
      if (box.isEmpty()) return;
      const center = box.getCenter(new THREE.Vector3());
      const size = box.getSize(new THREE.Vector3());
      const maxDim = Math.max(size.x, size.y, size.z) || 1;
      robot.position.sub(center);
      const dist = maxDim * 1.8;
      camera.position.set(dist * 0.6, dist * 0.5, dist * 0.9);
      controls.target.set(0, 0, 0);
      controls.update();
    }

    async function loadAsset(urdfPath: string) {
      setLoading(true);
      setError(null);
      setChecklist(null);
      setAssetName(urdfPath.split("/").slice(-3, -2)[0] ?? urdfPath);

      const s = sceneRef.current;
      if (!s) return;
      if (s.robot) {
        scene.remove(s.robot);
        s.robot = null;
      }

      const manager = new THREE.LoadingManager();
      const loader = new URDFLoader(manager);
      const fullUrl = `/catalog/${urdfPath}`;

      await new Promise<void>((resolve) => {
        loader.load(
          fullUrl,
          (robot: URDFRobotLike) => {
            scene.add(robot);
            fitCameraToRobot(robot);

            const joints: TeleopJointInfo[] = [];
            const parsedJoints: Record<string, ParsedJoint> = {};
            const jointValues: Record<string, number> = {};
            for (const [name, joint] of Object.entries(robot.joints)) {
              joints.push({
                name,
                type: joint.jointType,
                limits: {
                  lower: joint.limit.lower,
                  upper: joint.limit.upper,
                  effort: joint.limit.effort,
                  velocity: joint.limit.velocity,
                },
              });
              parsedJoints[name] = {
                name,
                jointType: joint.jointType,
                limit: { lower: joint.limit.lower, upper: joint.limit.upper },
                mimic: joint.mimicJoint ?? undefined,
              };
              jointValues[name] = 0;
            }

            s.robot = robot;
            s.joints = joints;
            s.jointValues = jointValues;

            const policy = resolvePolicy(readParams().policy);
            s.bindings = policy?.metadata.keyboard_bindings ?? [];
            setChecklist(runChecklist(parsedJoints, policy));

            setLoading(false);
            resolve();
          },
          undefined,
          (err: unknown) => {
            setError(err instanceof Error ? err.message : String(err));
            setLoading(false);
            resolve();
          },
        );
      });
    }

    const initialParams = readParams();
    void loadAsset(initialParams.urdf);

    window.__twinPreview = {
      loadAsset,
      getJointState: () => ({ ...(sceneRef.current?.jointValues ?? {}) }),
      setJoint: (name, value) => {
        const s = sceneRef.current;
        if (!s?.robot) return;
        s.jointValues[name] = value;
        s.robot.setJointValue(name, value);
      },
      getChecklistResult: () => checklist,
    };

    return () => {
      disposed = true;
      window.clearInterval(tickInterval);
      window.removeEventListener("resize", resize);
      window.removeEventListener("keydown", onKeyDown);
      window.removeEventListener("keyup", onKeyUp);
      renderer.dispose();
      mount.removeChild(renderer.domElement);
      delete window.__twinPreview;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- one-time scene setup
  }, []);

  // Keep window.__twinPreview.getChecklistResult reading current state without
  // re-running the whole scene-setup effect.
  useEffect(() => {
    if (window.__twinPreview) {
      window.__twinPreview.getChecklistResult = () => checklist;
    }
  }, [checklist]);

  return (
    <>
      <div ref={mountRef} style={{ width: "100%", height: "100%" }} />
      <StatusLine assetName={assetName} loading={loading} error={error} checklist={checklist} />
    </>
  );
}
