<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="generic_table" params="parent *origin">
    <joint name="table_base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="table_link" />
    </joint>

    <!-- Center of table -->
    <link name="table_link">
      <visual>
        <geometry>
          <box size = "0.61 1.52 0.02"/>
        </geometry>
        <material name="">
          <color rgba="0.8 0.8 0.8 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size = "0.61 1.52 0.02"/>
        </geometry>
      </collision>
    </link>

    <!-- Collision scene to prevent leaving the workspace -->
    <xacro:arg name="obstacle_height" default="1.0" />
    <xacro:arg name="obstacle_width" default="1.0" />
    <xacro:arg name="obstacle_wall_y" default="0.75" />

    <joint name="table_left_collision_wall_joint" type="fixed">
      <origin xyz="0 $(arg obstacle_wall_y) ${$(arg obstacle_height)/2}" rpy="0 0 0" />
      <parent link="table_link"/>
      <child link="table_left_collision_wall" />
    </joint>
    <link name="table_left_collision_wall">
      <!-- <visual>
        <geometry>
          <box size = "0.61 0.038 $(arg obstacle_height)"/>
        </geometry>
        <material name="">
          <color rgba="1.0 1.0 0 0.5"/>
        </material>
      </visual> -->
      <collision>
        <geometry>
          <box size = "$(arg obstacle_width) 0.038 $(arg obstacle_height)"/>
        </geometry>
      </collision>
    </link>
    <joint name="table_right_collision_wall_joint" type="fixed">
      <origin xyz="0 ${$(arg obstacle_wall_y)*-1} ${$(arg obstacle_height)/2}" rpy="0 0 0" />
      <parent link="table_link"/>
      <child link="table_right_collision_wall" />
    </joint>
    <link name="table_right_collision_wall">
      <!-- <visual>
        <geometry>
          <box size = "0.61 0.038 $(arg obstacle_height)"/>
        </geometry>
        <material name="">
          <color rgba="1.0 1.0 0 0.5"/>
        </material>
      </visual> -->
      <collision>
        <geometry>
          <box size = "$(arg obstacle_width) 0.038 $(arg obstacle_height)"/>
        </geometry>
      </collision>
    </link>
    <joint name="table_front_collision_wall_joint" type="fixed">
      <origin xyz="0.3 0 ${$(arg obstacle_height)/2}" rpy="0 0 0" />
      <parent link="table_link"/>
      <child link="table_front_collision_wall" />
    </joint>
    <link name="table_front_collision_wall">
      <!-- <visual>
        <geometry>
          <box size = "0.015 1.52 $(arg obstacle_height)"/>
        </geometry>
        <material name="">
          <color rgba="1.0 1.0 0 0.5"/>
        </material>
      </visual> -->
      <collision>
        <geometry>
          <box size = "0.015 1.52 $(arg obstacle_height)"/>
        </geometry>
      </collision>
    </link>

  </xacro:macro>
</robot>
